In [2]:
import pandas as pd

menu = pd.read_csv("restaurant_final.csv", encoding="utf-8-sig")
final = pd.read_csv("preprocessed_naver.csv", encoding="utf-8-sig")

In [4]:
final.head(1)

,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),전화번호,운영시간,총 리뷰 개수,소개,편의시설 및 서비스,주차 정보,이런점이 좋았어요,최신 300개 리뷰,좌석 정보,tfidf_features
0,63.02,서울특별시 마포구 서교동 399-9,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.383195,449648.516083,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291.0,홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...",음식이 맛있고 직원분들 친절해요 다음에도 올 생각 있음 추천합니다 음식도 빨리 나와...,"['카운터석', '입식', '바테이블']","2차로:0.05, ㅋㅋ:0.02, ㅎㅎ:0.02, ㅎㅎㅎ:0.00, ㅠㅠ:0.02,..."

In [5]:

final = final.merge(menu[['사업장명', '메뉴']], left_on="사업장명", right_on="사업장명", how='left')

In [6]:
final.head(1)

,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),전화번호,운영시간,총 리뷰 개수,소개,편의시설 및 서비스,주차 정보,이런점이 좋았어요,최신 300개 리뷰,좌석 정보,tfidf_features,메뉴
0,63.02,서울특별시 마포구 서교동 399-9,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.383195,449648.516083,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291.0,홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...",음식이 맛있고 직원분들 친절해요 다음에도 올 생각 있음 추천합니다 음식도 빨리 나와...,"['카운터석', '입식', '바테이블']","2차로:0.05, ㅋㅋ:0.02, ㅎㅎ:0.02, ㅎㅎㅎ:0.00, ㅠㅠ:0.02,...","[['아보카도크림새우', 19900], ['깐풍기', 18500], ['사천가지튀김..."

In [7]:
final.rename(columns={
    "사업장명": "name",
    "지번주소": "jibun_address",
    "도로명주소": "road_address",
    "업태구분명": "category",
    "전화번호": "phone",
    "운영시간": "business_hours",
    "총 리뷰 개수": "review_count",
    "소개": "description",
    "주차 정보": "parking",
    "좌석 정보": "seat_info",
    "최신 300개 리뷰": "latest_reviews",
    "소재지면적": "size",
    "편의시설 및 서비스" : "facilities",
    "이런점이 좋았어요": "very_good",
    "tfidf_features": "tfidf_features",
    "좌표정보(X)": "latitude",
    "좌표정보(Y)": "longitude",
    "메뉴" : "menu"
}, inplace=True)

In [8]:
final.head(1)

,size,jibun_address,road_address,name,category,latitude,longitude,phone,business_hours,review_count,description,facilities,parking,very_good,latest_reviews,seat_info,tfidf_features,menu
0,63.02,서울특별시 마포구 서교동 399-9,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.383195,449648.516083,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291.0,홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...",음식이 맛있고 직원분들 친절해요 다음에도 올 생각 있음 추천합니다 음식도 빨리 나와...,"['카운터석', '입식', '바테이블']","2차로:0.05, ㅋㅋ:0.02, ㅎㅎ:0.02, ㅎㅎㅎ:0.00, ㅠㅠ:0.02,...","[['아보카도크림새우', 19900], ['깐풍기', 18500], ['사천가지튀김..."

In [1]:
# 📌 변경된 데이터 저장
output_path = "final_updated.csv"
final.to_csv(output_path, index=False, encoding="utf-8-sig")

NameError: name 'final' is not defined

In [4]:
import pandas as pd

final = pd.read_csv("final_updated.csv", encoding = "utf-8-sig")
test = final.head(2)
output_path = "test.csv"
test.to_csv(output_path, index=False, encoding="utf-8-sig")

In [5]:
import pandas as pd

final = pd.read_csv("final_updated.csv", encoding = "utf-8-sig")

In [7]:
final["review_count"].sum()

169294.0