In [1]:
import pandas as pd

df = pd.read_csv("final_sql.csv",encoding="utf-8-sig")
url = pd.read_csv("link_url.csv",encoding="utf-8-sig")

In [4]:
df.head(1)
url.head(1)

,id,photo_url,road_address,name,size,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu,category,Processed,connect_url,img_urls
0,1,['https://search.pstatic.net/common/?autoRotat...,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,63.02,192669.3832,449648.5161,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"['음식이 맛있어요', '인테리어가 멋져요', '친절해요', '대화하기 좋아요']","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김...",중식,Yes,NaN,https://naver.me/GfCkgaiW

In [5]:
url = url.rename(columns={'img_urls': 'connect_urls'})

In [8]:
url.head(1)
url = url[["id","connect_urls"]]

In [10]:
missing_count = url['connect_urls'].isna().sum()
print(f"결측값 개수: {missing_count}")

결측값 개수: 0

In [11]:
df_merged = df.merge(url, on='id', how='left')

In [13]:
df_merged.head(3)
df_merged = df_merged.rename(columns={'connect_urls': 'connect_url'})

In [14]:
df_merged.head(3)

,id,photo_url,road_address,name,size,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu,category,connect_url
0,1,['https://search.pstatic.net/common/?autoRotat...,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,63.02,192669.3832,449648.5161,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"['음식이 맛있어요', '인테리어가 멋져요', '친절해요', '대화하기 좋아요']","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김...",중식,https://naver.me/GfCkgaiW
1,2,['https://search.pstatic.net/common/?autoRotat...,"서울특별시 마포구 양화로 81, H 스퀘어 102호,103호,104호,105호 (서교동)",탭샵바 합정점,610.52,192565.8569,449977.7782,0507-1467-0765,화: 11:00 - 24:00; 수: 11:00 - 24:00; 목: 11:00 -...,131,"['와인 페어링', '와인 페어링', '포장', '단체 이용 가능', '배달', '...",무료 주차 가능,"['술이 다양해요', '음식이 맛있어요', '인테리어가 멋져요', '음악이 좋아요']","['룸', '단체석', '카운터석', '테라스', '좌식', '1인석', '연인석']","[[""루꼴라 치즈 떡볶이"", 9900]]",한식,https://naver.me/5GpY7V7l
2,3,['https://search.pstatic.net/common/?autoRotat...,"서울특별시 마포구 와우산로29마길 7-8, 지1층 우측호 (서교동)",연남골목냉면,48.37,193472.1057,450345.4305,NaN,NaN,38,[],NaN,"['음식이 맛있어요', '재료가 신선해요', '양이 많아요', '혼밥하기 좋아요']",[],"[[""명태회냉면"", 10000], [""물냉면"", 8000], [""비빔냉면"", 800...",한식,https://naver.me/Fy2rVfBP

In [15]:
df_merged.to_csv("link_final_sql.csv", encoding="utf-8-sig",index = False)