In [132]:
import pandas as pd

final = pd.read_csv("preprocessed_naver.csv", encoding = "utf-8-sig")
id = pd.read_csv("SQL_DB.csv", encoding = "utf-8-sig")

In [129]:
id = id.drop(columns=["id"])

In [130]:
id.insert(0, 'id', range(1, len(id) + 1))

In [131]:
id.to_csv("SQL_DB.csv",encoding= "utf-8-sig",index=False)

In [135]:
id["name"]
final["name"]

0        라운지목화 합정관
1          탭샵바 합정점
2           연남골목냉면
3              유아하
4             증증일상
          ...
583             넌덕
584          족발애감동
585             이키
586    이가네 양꼬치 양갈비
587          같이양조장
Name: name, Length: 588, dtype: object

In [136]:
id[id["name"] == "모모유부 홍대점"]
final[final["name"] == "모모유부 홍대점"]

,size,road_address,name,category,latitude,longitude,phone,business_hours,review_count,description,latest_reviews,menu,keyword
70,32.84,"서울특별시 마포구 홍익로 10, 지1층 지129호 (서교동, 서교푸르지오)",모모유부 홍대점,한식,193187.803,450172.1789,02-334-8583,화: 11:00 - 21:00; 수: 11:00 - 21:00; 목: 11:00 -...,511,2018년부터 자리를 지키고있는\n홍대 혼밥 맛집 [유부초밥 전문점 모모유부] 입니...,"['항상 대기가 있어 기대 안하고 갔었는데 바로 입장 해서 좋았어요', '', '너...",NaN,"['무선 인터넷', '배달', '포장', '방문접수/출장', '예약', '남/녀 화..."

In [126]:
unmatched_names = set(id["name"]).symmetric_difference(set(final["name"]))
unmatched_names = set(final["name"]).symmetric_difference(set(id["name"]))
unmatched_names

{'플래닛'}

In [125]:
duplicates = id[id.duplicated(subset=["name"], keep=False)]

In [124]:
duplicates

Empty DataFrame
Columns: [size, road_address, name, category, latitude, longitude, phone, business_hours, review_count, description, latest_reviews, menu, keyword]
Index: []

In [98]:
unmatched_names

set()

In [106]:
id.head()

,id,size,road_address,name,category,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu
0,1,63.02,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.3832,449648.5161,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김..."
1,2,610.52,"서울특별시 마포구 양화로 81, H 스퀘어 102호,103호,104호,105호 (서교동)",탭샵바 합정점,한식,192565.8569,449977.7782,0507-1467-0765,화: 11:00 - 24:00; 수: 11:00 - 24:00; 목: 11:00 -...,131,"['와인 페어링', '전문 소믈리에', '포장', '단체 이용 가능', '배달', ...",무료 주차 가능,"[['""술이 다양해요""', 111], ['""음식이 맛있어요""', 99], ['""인테...","['룸', '단체석', '카운터석', '테라스', '좌식', '1인석', '연인석']","[[""루꼴라 치즈 떡볶이"", 9900]]"
2,3,48.37,"서울특별시 마포구 와우산로29마길 7-8, 지1층 우측호 (서교동)",연남골목냉면,한식,193472.1057,450345.4305,NaN,NaN,38,[],NaN,"[['""음식이 맛있어요""', 58], ['""재료가 신선해요""', 15], ['""양이...",[],"[[""명태회냉면"", 10000], [""물냉면"", 8000], [""비빔냉면"", 800..."
3,4,54.00,"서울특별시 마포구 독막로3길 24-10, 지1층 A호 (서교동)",유아하,중국식,192626.3225,449645.0116,0507-1432-7841,수: 17:00 - 24:00; 목: 17:00 - 24:00; 금: 17:00 -...,60,"['콜키지 가능', '생일 혜택', '단체 이용 가능']",주차 불가,"[['""음식이 맛있어요""', 60], ['""인테리어가 멋져요""', 38], ['""특...","['바테이블', '1인석', '테라스', '연인석', '카운터석', '좌식', '단...","[[""유아하 할머니의 훠궈"", 32900], [""우삼겹 후추탕"", 25000], [..."
4,5,93.82,"서울특별시 마포구 와우산로27길 62, 2층 (서교동)",증증일상,중국식,193340.6966,450339.4518,02-333-5888,화: 11:00 - 22:30; 수: 정기휴무 (매주 수요일); 목: 11:00 -...,476,"['포장', '배달', '무선 인터넷', '유아의자', '예약']",주차 불가,"[['""음식이 맛있어요""', 480], ['""친절해요""', 223], ['""특별한 ...",[],"[[""꽌탕바오(육즙 샤오롱바오)"", 7300], [""성젠바오(육즙 군만두)"", 70..."

In [105]:
id

,id,size,road_address,name,category,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu
0,1,63.02,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.3832,449648.5161,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김..."
1,2,610.52,"서울특별시 마포구 양화로 81, H 스퀘어 102호,103호,104호,105호 (서교동)",탭샵바 합정점,한식,192565.8569,449977.7782,0507-1467-0765,화: 11:00 - 24:00; 수: 11:00 - 24:00; 목: 11:00 -...,131,"['와인 페어링', '전문 소믈리에', '포장', '단체 이용 가능', '배달', ...",무료 주차 가능,"[['""술이 다양해요""', 111], ['""음식이 맛있어요""', 99], ['""인테...","['룸', '단체석', '카운터석', '테라스', '좌식', '1인석', '연인석']","[[""루꼴라 치즈 떡볶이"", 9900]]"
2,3,48.37,"서울특별시 마포구 와우산로29마길 7-8, 지1층 우측호 (서교동)",연남골목냉면,한식,193472.1057,450345.4305,NaN,NaN,38,[],NaN,"[['""음식이 맛있어요""', 58], ['""재료가 신선해요""', 15], ['""양이...",[],"[[""명태회냉면"", 10000], [""물냉면"", 8000], [""비빔냉면"", 800..."
3,4,54.00,"서울특별시 마포구 독막로3길 24-10, 지1층 A호 (서교동)",유아하,중국식,192626.3225,449645.0116,0507-1432-7841,수: 17:00 - 24:00; 목: 17:00 - 24:00; 금: 17:00 -...,60,"['콜키지 가능', '생일 혜택', '단체 이용 가능']",주차 불가,"[['""음식이 맛있어요""', 60], ['""인테리어가 멋져요""', 38], ['""특...","['바테이블', '1인석', '테라스', '연인석', '카운터석', '좌식', '단...","[[""유아하 할머니의 훠궈"", 32900], [""우삼겹 후추탕"", 25000], [..."
4,5,93.82,"서울특별시 마포구 와우산로27길 62, 2층 (서교동)",증증일상,중국식,193340.6966,450339.4518,02-333-5888,화: 11:00 - 22:30; 수: 정기휴무 (매주 수요일); 목: 11:00 -...,476,"['포장', '배달', '무선 인터넷', '유아의자', '예약']",주차 불가,"[['""음식이 맛있어요""', 480], ['""친절해요""', 223], ['""특별한 ...",[],"[[""꽌탕바오(육즙 샤오롱바오)"", 7300], [""성젠바오(육즙 군만두)"", 70..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,600,28.95,"서울특별시 마포구 월드컵로5길 74 (합정동, 1층일부)",넌덕,일식,191842.6215,449832.2814,0507-1334-5187,목: 11:30 - 20:30; 금: 11:30 - 20:30; 토: 12:00 -...,192,"['포장', '무선 인터넷', '배달']",무료 주차 가능,"[['""음식이 맛있어요""', 237], ['""친절해요""', 127], ['""재료가 ...",[],"[[""2달의버거"", 10900], [""넌덕버거"", 8900], [""치즈버거"", 79..."
600,601,59.46,"서울특별시 마포구 독막로 55 (합정동, 나동 1층 일부)",족발애감동,한식,192810.7165,449544.2099,02-322-5257,수: 17:00 - 04:00; 목: 17:00 - 04:00; 금: 17:00 -...,90,[],NaN,"[['""음식이 맛있어요""', 83], ['""단체모임 하기 좋아요""', 38], ['...",[],"[[""냉채족발"", 37000], [""돼지김치찌개"", 7000], [""매운 족 (대)..."
601,602,75.11,"서울특별시 마포구 성지길 36-20, 지1층 (합정동)",이키,일식,192212.9099,449448.6408,NaN,수: 18:00 - 01:00; 목: 18:00 - 01:00; 금: 18:00 -...,127,"['예약', '단체 이용 가능']",NaN,"[['""음식이 맛있어요""', 144], ['""특별한 메뉴가 있어요""', 78], [...",[],"[[""제철사시미"", 30000], [""완도김파스타"", 16000], [""멘치까스"",..."
602,603,137.00,"서울특별시 마포구 월드컵로1길 14, 지1층 B118-1, B118-2호 (합정동,...",이가네 양꼬치 양갈비,중국식,192171.2354,449751.4870,02-337-3688,NaN,559,[],주차 가능,"[['""마사지가 시원해요""', 346], ['""친절해요""', 276], ['""맞춤 ...",[],"[[""양왕갈비 (250g)"", 26000], [""양등심꼬치 (250g)"", 2300..."
603,604,90.47,"서울특별시 마포구 양화진4길 17, 동원빌딩 4층 (합정동)",같이양조장,한식,192087.9368,449456.8027,0507-1493-9991,목: 10:00 - 18:00; 금: 10:00 - 18:00; 토: 10:00 -...,128,"['포장', '예약']",무료 주차 가능,[],[],[]

In [104]:
unmatched_names

Empty DataFrame
Columns: [id, size, road_address, name, category, latitude, longitude, phone, business_hours, review_count, facilities, parking, very_good, seat_info, menu]
Index: []

In [102]:
id["name"]
#final["name"]

0        라운지목화 합정관
1          탭샵바 합정점
2           연남골목냉면
3              유아하
4             증증일상
          ...
599             넌덕
600          족발애감동
601             이키
602    이가네 양꼬치 양갈비
603          같이양조장
Name: name, Length: 604, dtype: object

In [142]:
id["category"]
final["category"]

0      중국식
1       한식
2       한식
3      중국식
4      중국식
      ...
583     일식
584     한식
585     일식
586    중국식
587     한식
Name: category, Length: 588, dtype: object

In [143]:
merged_df = id.merge(final[["name", "category"]], on="name", how="left", suffixes=("_id", "_final"))

In [147]:
merged_df = merged_df.drop(columns=["category_id"])

In [151]:
merged_df.rename(columns={"category_final": "category"}, inplace=True)

In [153]:
merged_df.head(1)

,id,size,road_address,name,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu,category
0,1,63.02,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,192669.3832,449648.5161,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김...",중식

In [154]:
merged_df.to_csv("SQL_DB.csv",encoding= "utf-8-sig",index=False)

In [160]:
final = final.merge(merged_df[["name","id"]], on = "name", how="left")

In [162]:
final.to_csv("preprocessed_naver.csv",encoding= "utf-8-sig",index=False)

In [28]:
# Merge final with restaurants based on 'name' to check missing IDs
merged = final.merge(id[['id', 'name']], on='name', how='left')
merged[merged['id'].isna()]

,Unnamed: 0,size,road_address,name,category,latitude,longitude,phone,business_hours,review_count,description,latest_reviews,menu,keyword,id
73,71,32.84,"서울특별시 마포구 홍익로 10, 지1층 지129호 (서교동, 서교푸르지오)",모모유부 홍대점,한식,193187.803,450172.1789,02-334-8583,화: 11:00 - 21:00; 수: 11:00 - 21:00; 목: 11:00 -...,511,2018년부터 자리를 지키고있는\n홍대 혼밥 맛집 [유부초밥 전문점 모모유부] 입니...,"['항상 대기가 있어 기대 안하고 갔었는데 바로 입장 해서 좋았어요', '', '너...",NaN,"['무선 인터넷', '배달', '포장', '방문접수/출장', '예약', '남/녀 화...",NaN

In [14]:
final = final[["name","description","latest_reviews"]]

In [23]:
id = pd.read_csv("SQL_DB.csv", encoding = "utf-8-sig")

In [16]:
id.head(2)

,Unnamed: 0,id,size,road_address,name,category,latitude,longitude,phone,business_hours,review_count,facilities,parking,very_good,seat_info,menu
0,0,1,63.02,"서울특별시 마포구 양화로6길 57-12, 1층 (서교동)",라운지목화 합정관,중국식,192669.383195,449648.516083,0507-1469-7338,화: 17:00 - 02:00; 수: 17:00 - 02:00; 목: 17:00 -...,291.0,"['단체 이용 가능', '예약', '무선 인터넷']",주차 불가,"[['""음식이 맛있어요""', 293], ['""인테리어가 멋져요""', 168], ['...","['카운터석', '입식', '바테이블']","[[""아보카도크림새우"", 19900], [""깐풍기"", 18500], [""사천가지튀김..."
1,1,2,610.52,"서울특별시 마포구 양화로 81, H 스퀘어 102호,103호,104호,105호 (서교동)",탭샵바 합정점,한식,192565.856895,449977.778212,0507-1467-0765,화: 11:00 - 24:00; 수: 11:00 - 24:00; 목: 11:00 -...,131.0,"['와인 페어링', '전문 소믈리에', '포장', '단체 이용 가능', '배달', ...",무료 주차 가능,"[['""술이 다양해요""', 111], ['""음식이 맛있어요""', 99], ['""인테...","['룸', '단체석', '카운터석', '테라스', '좌식', '1인석', '연인석']","[[""루꼴라 치즈 떡볶이"", 9900]]"

In [7]:
#id = id[["id","name"]]

In [17]:
final

,name,description,latest_reviews
0,라운지목화 합정관,홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...,"['음식이 맛있고 알바생이 매우 친절하고 귀여워요', '뭐야 먹다보니 이거남음 이게..."
1,탭샵바 합정점,"'wine is second americano'\n\n안녕하세요,\n\n와인을 더 ...","['', '와인도 분위기도 너무 좋아요', '친절하고 노래도 좋고 너무 좋아요', ..."
2,연남골목냉면,NaN,"['냉면 배달 맛집 입니다', '여기 넘 좋아요 테이블 개지만 맛있게 먹고 왔어요'..."
3,유아하,"합정에서 만나는 진짜 대만의 맛, 유아하\n\n3대째 내려온 할머니의 레시피로, 깊...","['', '마라를 안좋아하는 남자 둘이서도 진짜 맛있게 잘먹었습니다 다른 메뉴들도 ..."
4,증증일상,"蒸蒸日上(증증일상) 이름 유래:\n蒸은 '찔, 증'이라는 한자로 '찌다', '데우다...","['맛이 좋아요', '토마토계란볶음면 괜찮네요 만두도 맛있어요', '가려던 곳 웨이..."
...,...,...,...
597,넌덕,안녕하세요 넌-덕 입니다\n오리사장의 햄버거 집입니다\n공간이 협소해 애견동반은 어...,"['', '말랑쫀득 버거번 육즙 터지는 패티 달큰하게 구운 양파 간 잘 된 소스 조..."
598,족발애감동,국내산 생족을 매일 직접 삶는 족발의 참맛을 볼 수 있는 홍대 족발 메카!,"['', '친구들하고 다같이 갔는데 야장이여서 너무 좋았어요 맛도 괜찮았어요', '..."
599,이키,"합정동 이자카야 이키입니다.\n와인,사케,생맥주,하이볼등 다양한주류를\n제철식재료를...","['', '노무 좋아요 튿히 완도김파스타 진짜 맛있어요', '고등어봉초밥 넘 맛있었..."
600,이가네 양꼬치 양갈비,* 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...,['시설이 깔끔하고 룸마다 의류관리기가 있어요 직원분들도 모두 친절하고 마사지도 늘...
601,같이양조장,_\n옛 문헌 속에 존재하는 전통주를 기반으로 다양한 부재료와 조합해 현대적으로 재...,"['', '매우 친절하시고 깔끔했습니다 잔들도 고급스럽고 예쁩니다', '너무 재밌는..."

In [9]:
final_updated = final.merge(id[['id', 'name']], on='name', how='left')

In [10]:
final_updated

,name,description,latest_reviews,id
0,라운지목화 합정관,홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...,"['음식이 맛있고 알바생이 매우 친절하고 귀여워요', '뭐야 먹다보니 이거남음 이게...",1.0
1,탭샵바 합정점,"'wine is second americano'\n\n안녕하세요,\n\n와인을 더 ...","['', '와인도 분위기도 너무 좋아요', '친절하고 노래도 좋고 너무 좋아요', ...",2.0
2,연남골목냉면,NaN,"['냉면 배달 맛집 입니다', '여기 넘 좋아요 테이블 개지만 맛있게 먹고 왔어요'...",3.0
3,유아하,"합정에서 만나는 진짜 대만의 맛, 유아하\n\n3대째 내려온 할머니의 레시피로, 깊...","['', '마라를 안좋아하는 남자 둘이서도 진짜 맛있게 잘먹었습니다 다른 메뉴들도 ...",4.0
4,증증일상,"蒸蒸日上(증증일상) 이름 유래:\n蒸은 '찔, 증'이라는 한자로 '찌다', '데우다...","['맛이 좋아요', '토마토계란볶음면 괜찮네요 만두도 맛있어요', '가려던 곳 웨이...",5.0
...,...,...,...,...
627,넌덕,안녕하세요 넌-덕 입니다\n오리사장의 햄버거 집입니다\n공간이 협소해 애견동반은 어...,"['', '말랑쫀득 버거번 육즙 터지는 패티 달큰하게 구운 양파 간 잘 된 소스 조...",604.0
628,족발애감동,국내산 생족을 매일 직접 삶는 족발의 참맛을 볼 수 있는 홍대 족발 메카!,"['', '친구들하고 다같이 갔는데 야장이여서 너무 좋았어요 맛도 괜찮았어요', '...",605.0
629,이키,"합정동 이자카야 이키입니다.\n와인,사케,생맥주,하이볼등 다양한주류를\n제철식재료를...","['', '노무 좋아요 튿히 완도김파스타 진짜 맛있어요', '고등어봉초밥 넘 맛있었...",606.0
630,이가네 양꼬치 양갈비,* 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...,['시설이 깔끔하고 룸마다 의류관리기가 있어요 직원분들도 모두 친절하고 마사지도 늘...,607.0
631,같이양조장,_\n옛 문헌 속에 존재하는 전통주를 기반으로 다양한 부재료와 조합해 현대적으로 재...,"['', '매우 친절하시고 깔끔했습니다 잔들도 고급스럽고 예쁩니다', '너무 재밌는...",608.0

In [12]:
final_updated[final_updated['id'].isna()]

,name,description,latest_reviews,id
18,지원,NaN,"['', '레몬진 있음', '홍대 편의점 가격 날뛰는데 여긴 새로 생겨서 가격 안비...",NaN
74,모모유부,2018년부터 자리를 지키고있는\n홍대 혼밥 맛집 [유부초밥 전문점 모모유부] 입니...,"['항상 대기가 있어 기대 안하고 갔었는데 바로 입장 해서 좋았어요', '', '너...",NaN
287,버뮤다,+++ 홍대 최대 규모 일렉 & 힙합 클럽 +++\n\n[ CLUB BERMUDA_...,[],NaN
310,고고스,NaN,"['', '저의 최애', '친절해요', '좋아요', '넘 재믹어요', '굳', '좋...",NaN
338,??DOPE),홍대에서 볼 수 없는 색다른 분위기와 가성비 좋은 위스키&칵테일바.\n다양한 플레이...,['사장님이 진짜 친절하구 가게 매장 노래랑 분위기가 진짜 취저 담에 홍대오면 또 ...,NaN
342,에잇스톤스,NaN,"['', '홍대에곱창머리끈샀네요', '고맙습니다', '급하게 우산 삼', '귀엽고 ...",NaN
541,마부자생삼겹살,* 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...,['시설이 깔끔하고 룸마다 의류관리기가 있어요 직원분들도 모두 친절하고 마사지도 늘...,NaN
563,포로이,* 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...,['시설이 깔끔하고 룸마다 의류관리기가 있어요 직원분들도 모두 친절하고 마사지도 늘...,NaN

In [175]:
import pandas as pd

df = pd.read_csv("pre_embedding.csv", encoding = "utf-8-sig")

In [176]:
df.columns

Index(['size', 'road_address', 'name', 'category', 'latitude', 'longitude',
       'phone', 'business_hours', 'review_count', 'description',
       'latest_reviews', 'menu', 'keyword', 'id'],
      dtype='object')

In [177]:
df = df[["id","description","latest_reviews"]]

In [179]:
df["latest_reviews"] = df["latest_reviews"].apply(lambda x: eval(x) if isinstance(x, str) else x)  # Convert string lists to actual lists
latest_df = df[["id","latest_reviews"]].explode("latest_reviews")
description_df = df[["id","description"]]

In [181]:
description_df

      id                                        description
0      1  홍콩누와르 요리주점 라운지목화\n\n'우리는 그 시절 홍콩이 그리웠다.'\n\n홍콩...
1      2  'wine is second americano'\n\n안녕하세요,\n\n와인을 더 ...
2      3                                                NaN
3      4  합정에서 만나는 진짜 대만의 맛, 유아하\n\n3대째 내려온 할머니의 레시피로, 깊...
4      5  蒸蒸日上(증증일상) 이름 유래:\n蒸은 '찔, 증'이라는 한자로 '찌다', '데우다...
..   ...                                                ...
583  584  안녕하세요 넌-덕 입니다\n오리사장의 햄버거 집입니다\n공간이 협소해 애견동반은 어...
584  585          국내산 생족을 매일 직접 삶는 족발의 참맛을 볼 수 있는 홍대 족발 메카!
585  586  합정동 이자카야 이키입니다.\n와인,사케,생맥주,하이볼등 다양한주류를\n제철식재료를...
586  587  * 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...
587  588  _\n옛 문헌 속에 존재하는 전통주를 기반으로 다양한 부재료와 조합해 현대적으로 재...

[588 rows x 2 columns]

In [184]:

latest_df.rename(columns={"latest_reviews": "embedded"}, inplace=True)
description_df.rename(columns={"description": "embedded"}, inplace=True)

/var/folders/tf/02_6lkvd73nbp9k5fyfj80fh0000gn/T/ipykernel_9491/1739544371.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  description_df.rename(columns={"description": "embedded"}, inplace=True)

In [185]:
df_combined = pd.concat([latest_df, description_df], ignore_index=True)

In [186]:
df_combined

        id                                           embedded
0        1                          음식이 맛있고 알바생이 매우 친절하고 귀여워요
1        1                          뭐야 먹다보니 이거남음 이게 합정역 술집 인가
2        1                             가게 분위기도 좋고 음식도 너무 맛있어요
3        1                                 분위기도 좋고 안주 너무 맛있어요
4        1                                         데이트 하기 좋네요
...    ...                                                ...
35941  584  안녕하세요 넌-덕 입니다\n오리사장의 햄버거 집입니다\n공간이 협소해 애견동반은 어...
35942  585          국내산 생족을 매일 직접 삶는 족발의 참맛을 볼 수 있는 홍대 족발 메카!
35943  586  합정동 이자카야 이키입니다.\n와인,사케,생맥주,하이볼등 다양한주류를\n제철식재료를...
35944  587  * 새로운 매장 위치\n마포한강1차푸르지오 ( 딜라이트 스퀘어 1차 )\n\n지하철...
35945  588  _\n옛 문헌 속에 존재하는 전통주를 기반으로 다양한 부재료와 조합해 현대적으로 재...

[35946 rows x 2 columns]

In [187]:
df_combined.to_csv("pre_embedding_ready.csv",encoding="utf-8-sig",index=False)

In [188]:
import pandas as pd

embedding = pd.read_csv("embedded_data.csv", encoding = "utf-8-sig")

In [194]:
embedding[embedding["embedding"].isna]

TypeError: Series.isna() takes 1 positional argument but 2 were given

In [197]:
embedding[embedding["embedding"].isna()]

        id                                           embedded embedding
0        1                          음식이 맛있고 알바생이 매우 친절하고 귀여워요       NaN
1        1                          뭐야 먹다보니 이거남음 이게 합정역 술집 인가       NaN
2        1                             가게 분위기도 좋고 음식도 너무 맛있어요       NaN
3        1                                 분위기도 좋고 안주 너무 맛있어요       NaN
4        1                                         데이트 하기 좋네요       NaN
...    ...                                                ...       ...
35907  550                 안녕하세요.\n절두산 성지 근처에 위치한 중식 전문점 입니다.       NaN
35908  551                 망원정사거리의 생선맛집\n\n인스타 - momhand_fish       NaN
35909  552  95년부터 19년간 종로 관철동 골목을 지켰던 비앤비가 돌아왔습니다. 전문 바텐더가...       NaN
35938  581  슬오라는 SLICE OF LIFE의 준말로 인생의 한 토막, 한 장면이라는 뜻을 지...       NaN
35939  582        돈까스집입니당\n\n14시 30분\n\n20시\n\n가 라스트오다 시간입니다.       NaN

[498 rows x 3 columns]

In [198]:
dropped = embedding[embedding["embedding"].isna()]

In [200]:
dropped.to_csv("dropped.csv", encoding="utf-8-sig", index=False)

In [212]:
test = pd.read_csv("embedded_dropped_data.csv", encoding="utf-8-sig")

In [213]:
test["id"]

0        1
1        1
2        1
3        1
4        1
      ...
493    550
494    551
495    552
496    581
497    582
Name: id, Length: 498, dtype: int64

In [214]:
test[test["embedding"].isna()]

      id embedded embedding
70     2      NaN       NaN
141   56      NaN       NaN
147  206      NaN       NaN
234  284      NaN       NaN
281  357      NaN       NaN
300  394      NaN       NaN
302  396      NaN       NaN
304  398      NaN       NaN
309  405      NaN       NaN
362  518      NaN       NaN
363  519      NaN       NaN
364  520      NaN       NaN
406   12      NaN       NaN
412  101      NaN       NaN
414  128      NaN       NaN
416  130      NaN       NaN
417  131      NaN       NaN
424  217      NaN       NaN
427  220      NaN       NaN
428  221      NaN       NaN
435  276      NaN       NaN
438  279      NaN       NaN
440  281      NaN       NaN
446  331      NaN       NaN
449  334      NaN       NaN
450  335      NaN       NaN
453  338      NaN       NaN
454  339      NaN       NaN
455  340      NaN       NaN
462  367      NaN       NaN
467  372      NaN       NaN
472  426      NaN       NaN
473  427      NaN       NaN
490  547      NaN       NaN

In [240]:
total = pd.read_csv("embedded_data.csv",encoding="utf-8-sig")
drop = pd.read_csv("embedded_dropped_data.csv")

In [241]:
total.head()

   id                   embedded embedding
0   1  음식이 맛있고 알바생이 매우 친절하고 귀여워요       NaN
1   1  뭐야 먹다보니 이거남음 이게 합정역 술집 인가       NaN
2   1     가게 분위기도 좋고 음식도 너무 맛있어요       NaN
3   1         분위기도 좋고 안주 너무 맛있어요       NaN
4   1                 데이트 하기 좋네요       NaN

In [229]:
total_cleaned = total.dropna(subset=["embedded"])

In [231]:
total_cleaned.to_csv("embedded_data.csv",encoding="utf-8-sig",index=False)

In [234]:
total[total["embedded"].isna()]

Empty DataFrame
Columns: [id, embedded, embedding]
Index: []

In [222]:
drop.head()

,id,embedded,embedding
0,1,음식이 맛있고 알바생이 매우 친절하고 귀여워요,"[0.030689973384141922, -0.02415662817656994, -..."
1,1,뭐야 먹다보니 이거남음 이게 합정역 술집 인가,"[-0.005963920149952173, -0.02691671811044216, ..."
2,1,가게 분위기도 좋고 음식도 너무 맛있어요,"[-0.004467054735869169, -0.06777255982160568, ..."
3,1,분위기도 좋고 안주 너무 맛있어요,"[0.021068671718239784, -0.029414284974336624, ..."
4,1,데이트 하기 좋네요,"[-0.016752153635025024, -0.044336266815662384,..."

In [235]:
total = total.merge(drop[["embedded", "embedding"]], on="embedded", how="left")

In [242]:
# Merge and directly update the 'embedding' column
total = total.merge(drop[["embedded", "embedding"]], on="embedded", how="left", suffixes=("", "_drop"))

# Fill missing values in 'embedding' with values from 'embedding_drop'
total["embedding"] = total["embedding"].combine_first(total["embedding_drop"])

# Drop the extra column
total.drop(columns=["embedding_drop"], inplace=True)

In [244]:
total[total["embedding"].isna()]

Empty DataFrame
Columns: [id, embedded, embedding]
Index: []

In [245]:
total.to_csv("embedded_data.csv", encoding="utf-8-sig", index=False)